# ====================================
# SITE INFORMATION
# ====================================
site_name: مقالات المكتب المصرى للتطوير الصناعي # The main title of your website
site_description: مقالات المكتب المصرى للتطوير الصناعي # Brief description
site_author: م-محمود مرزوق

theme:
  name: material
  language: ar
  direction: rtl

  font:
    text: Tajawal
    code: Roboto Mono

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: تفعيل الوضع الداكن
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: تفعيل الوضع المضيء

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: ar

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
