# ====================================
# SITE INFORMATION
# ====================================
site_name: مقالات المكتب المصرى للتطوير الصناعي
site_description: مقالات المكتب المصرى للتطوير الصناعي
site_author: م-محمود مرزوق

# ====================================
# UI, HEADERS, AND THEME
# ====================================
theme:
  name: material
  language: ar
  direction: rtl
  
  # Injecting your Logo
  logo: assets/logo.png
  favicon: assets/logo.png
  
  font:
    text: Tajawal
    code: Roboto Mono
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: تفعيل الوضع الداكن
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: تفعيل الوضع المضيء

  features:
    - navigation.top              
    - header.autohide             
    - search.suggest              
    - search.highlight            

plugins:
  - search:
      lang: ar

markdown_extensions:
  - tables
  - admonition
  - attr_list                   
  - md_in_html                  

# ====================================
# FOOTER SOCIAL LINKS
# ====================================
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://egybid.com/
      name: Website
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Marzouk01272873007/
      name: Facebook
